### ISSUE TITLE
Feat: Add borders/dividers for views

### ISSUE THREAD

**Issue by LucasV94** [Crevas/5-3-1-Dinner#9]
- Add separators for the EditText and TextViews

This will allow for easier clicking, and better visuals

**Comment by SethC94** [comment]
Im pushing a commit with borders set around the TextViews, but im not setting this issue as fixed because I still need to create states for the TextViews for when a view is selected. Currently just sets background to color primary when clicked.

**Comment by SethC94** [comment]
issue resolved on 5-30-17
waiting merge to master branch
